include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Avoid relative imports for files in lib/
    always_use_package_imports: true
    
    # Prefer const constructors
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    
    # Documentation
    public_member_api_docs: false
    
    # Style
    prefer_single_quotes: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    unnecessary_lambdas: true
    unnecessary_this: true
    
    # Null safety
    avoid_null_checks_in_equality_operators: true
    
    # Imports
    directives_ordering: true
    sort_child_properties_last: true
    
    # Avoid
    avoid_print: true
    avoid_empty_else: true
    avoid_returning_null_for_future: true
    avoid_type_to_string: true
    
    # Prefer
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_iterable_whereType: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
